package com.program;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;

//Serialization is process of converting an object into its bytestream. 
//Stream is continuous flow of data.
//An object needs to be converted into some chunks of data to transfer
//it over a network and send or receive.

public class SerializationDemo {

	public static void main(String[] args) throws IOException {
		//its a class which can create a file automatically
		FileOutputStream file = new FileOutputStream("josh.txt");
		
		
		//I have a student object and I am trying to convert that object into bytestream,
		//and to demonstrate this, I need a file where I can store the generated bytestream.
		//That's the reason I have the fileoutputstream class which can create a file and store the value.
		
		//We need a class which is capable of converting the object into bytestream.
		ObjectOutputStream obj = new ObjectOutputStream(file);
		
		Student s = new Student();
		s.setRoll_number(1500);
		s.setName("Josh");
		s.setAddress("Centreville");
		s.setPhone_number(000_000_0000);
		s.setMajor("CS");
		s.setMinor("BS");
		
		obj.writeObject(s);
		
	}
}